### ISSUE TITLE
Arch support

### ISSUE THREAD

**Issue by robborrego** [lighttroupe/luz-next#16]
Hello. I'm interested in using your software on my main Arch-based Linux machine. It appears some of the pages required for install are not in the Arch repositories. Is it possible to list install instructions for Arch-based systems? Thanks!

**Comment by lighttroupe** [comment]
I don't use Arch so I don't know how to get Luz working there.

If you come up with the instructions I'd put them on the page for others.

**Comment by lighttroupe** [comment]
Luz 3 is in the works built on the Godot game engine, so it runs on all flavors of Linux, OSX, Windows, and more.
